# Generated by Django 4.0.2 on 2022-03-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='children',
        ),
    ]
