# Generated by Django 4.0.2 on 2022-03-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_delete_data_remove_topic_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
