# Generated by Django 4.0.2 on 2022-03-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0004_uploadtopics_remove_topic_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtopics',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
